Enrico Hartanto (C14180013), Henry Wicaksono (C14180014), Gregorius Kevin K (C14180057)

# Numpy

Untuk bekerja dengan angka menggunakan Python. Jauh lebih cepat karena diperlakukan sebagai int/float, bukan object seperti apabila menggunakan Python biasa

## Installation 

conda install numpy atau pip install numpy

## Import

In [1]:
import numpy as np

## Numpy Speed Vs Python List Speed

In [2]:
import time

size = 1000000  

In [3]:
list1 = range(size)
list2 = range(size)

initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

print("Time taken by Lists :", 
      (time.time() - initialTime),
      "seconds")

Time taken by Lists : 0.1488938331604004 seconds


In [4]:
array1 = np.arange(size)  
array2 = np.arange(size)

initialTime = time.time()
resultantArray = array1 * array2

print("Time taken by NumPy Arrays :",
      (time.time() - initialTime),
      "seconds")

Time taken by NumPy Arrays : 0.0039882659912109375 seconds


## Membuat Array 1D

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

## Membuat Array 2D

In [6]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Membuat Array dengan Range Tertentu

In [7]:
a = np.arange(3)
print(a)
a = np.arange(3.0)
print(a)
a = np.arange(3,7)
print(a)
a = np.arange(3,7,2)
print(a)

[0 1 2]
[0. 1. 2.]
[3 4 5 6]
[3 5]


## Membuat Array dengan Shape Tertentu

In [8]:
a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
<class 'numpy.ndarray'>


## Membuat Array dengan Datatype Tertentu

In [9]:
a = np.arange(15, dtype=float).reshape(3, 5)
print(a)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


## Membuat Array Berisi 0.0 atau 1.0

In [10]:
a = np.zeros((3,4))
print(a)
a = np.ones((5))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]


## Membuat Array dengan Interval Linear

In [11]:
a = np.linspace(0, 2, 7)
print(a)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]


## Membuat Array dengan Interval Logaritmik

In [12]:
a = np.logspace(1, 2, num=5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


## Membuat Array dengan Element Random

In [13]:
a = np.random.randint(1,10,24).reshape(2,3,4)
print(a)

[[[9 4 6 1]
  [8 3 5 2]
  [8 5 2 8]]

 [[3 1 5 2]
  [6 7 2 4]
  [6 7 6 5]]]


## ==================================== 

## Konversi Python List ke Numpy Array

In [14]:
a=[[1,2,3],[4,5,6]]
b=np.asarray(a)
c=np.asarray(a,dtype=float)
print(a)
print(type(a))
print()
print(b)
print(type(b))
print()
print(c)
print(type(c))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>


## Slicing

In [15]:
x = np.arange(10)
print(x)
print()
print(x[2])
print()
print(x[-2])
print()
print(x[2:5])
print()
print(x[1:7:2])
print()
x.shape = (2,5)
print(x)
print()
print(x[0])

[0 1 2 3 4 5 6 7 8 9]

2

8

[2 3 4]

[1 3 5]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4]


In [16]:
y = np.arange(35).reshape(5,7)
print(y)
print()
print(y[1:5:2])
print()
print(y[1:5:2,::3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

[[ 7  8  9 10 11 12 13]
 [21 22 23 24 25 26 27]]

[[ 7 10 13]
 [21 24 27]]


## Indexing

In [17]:
x = np.arange(10,1,-1)
print(x)
print()
print(np.array([3,3,-3,8]))
print()
print(x[np.array([3,3,-3,8])])
print()
print(np.array([[1,1],[2,3]]))
print()
print(x[np.array([[1,1],[2,3]])])

[10  9  8  7  6  5  4  3  2]

[ 3  3 -3  8]

[7 7 4 2]

[[1 1]
 [2 3]]

[[9 9]
 [8 7]]


In [18]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]
print(x)
print()
print(y)

[[1 2]
 [3 4]
 [5 6]]

[1 4 5]


In [19]:
y = np.arange(35).reshape(5,7)
print(y)
print()
print(y[0:2,1:3])
print()
print(y[[0,2,4], [0,1,2]])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

[[1 2]
 [8 9]]

[ 0 15 30]


## Mengambil Nilai di Pojok Matriks dengan Indexing

In [20]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],
 [ 6, 7, 8],[ 9, 10, 11]])
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print(x)
print()
print(rows)
print()
print(cols)
print()
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[0 0]
 [3 3]]

[[0 2]
 [0 2]]

[[ 0  2]
 [ 9 11]]


## ==================================== 

## Boolean Indexing

In [21]:
x = np.arange(12).reshape(4,3)
print(x)
print(x>5)
print(x[x>5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]


## Filter Data dengan Boolean Indexing

In [22]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a)
b = a[~np.isnan(a)]
print(~np.isnan(a))
print(b)

[nan  1.  2. nan  3.  4.  5.]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


## Deep Copy

In [23]:
a = np.random.randint(1,10,24).reshape(2,3,4)
b = a.flatten() #deep copy
b[0] = 0
print(a)
print(b)

[[[6 5 7 5]
  [2 8 4 6]
  [1 6 3 6]]

 [[4 4 6 8]
  [4 7 6 5]
  [1 4 8 9]]]
[0 5 7 5 2 8 4 6 1 6 3 6 4 4 6 8 4 7 6 5 1 4 8 9]


## Shallow Copy

In [24]:
a = np.random.randint(1,10,24).reshape(2,3,4)
b = a.ravel() #shallow copy
b[0] = 0
print(a)
print(b)

[[[0 8 7 5]
  [7 8 6 5]
  [4 5 9 7]]

 [[3 2 2 3]
  [2 7 6 5]
  [7 8 2 9]]]
[0 8 7 5 7 8 6 5 4 5 9 7 3 2 2 3 2 7 6 5 7 8 2 9]


## Transpose Matrix

In [25]:
a = np.random.randint(1,10,24).reshape(2,3,4)
print(a)
print(a.T)
print(a.transpose())

[[[9 6 3 2]
  [1 4 5 8]
  [6 8 6 1]]

 [[8 7 7 5]
  [3 7 5 8]
  [7 8 5 1]]]
[[[9 8]
  [1 3]
  [6 7]]

 [[6 7]
  [4 7]
  [8 8]]

 [[3 7]
  [5 5]
  [6 5]]

 [[2 5]
  [8 8]
  [1 1]]]
[[[9 8]
  [1 3]
  [6 7]]

 [[6 7]
  [4 7]
  [8 8]]

 [[3 7]
  [5 5]
  [6 5]]

 [[2 5]
  [8 8]
  [1 1]]]


## Link Documentation Numpy

https://numpy.org/doc/